
name: Deploy static website to Azure Web App

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # No Node.js setup or build needed for static sites

      - name: Upload to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: '<YOUR_AZURE_APP_SERVICE_NAME>'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
